## USB port
# port: /dev/ttyUSB0
port: /dev/rfcomm0

rawdata_filename: imuONE.csv
number_of_samples: 2000
##default_data_stream_path: (dont use a relative path ~/catkin_ws/src/razor_imu_9dof)
main_data_stream_path: /home/map479/catkin_ws/src/razor_imu_9dof

# main_data_stream_path: /home/map479-admin/mxochicale/phd/ros/ros_razor/table_tennis/
# main_data_stream_path: /home/map479-admin/mxochicale/phd/ros/ros_razor/FourRazorsData


##### Calibration ####
### accelerometer
accel_x_min: -250.0
accel_x_max: 250.0
accel_y_min: -250.0
accel_y_max: 250.0
accel_z_min: -250.0
accel_z_max: 250.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: false
magn_ellipsoid_center: [0, 0, 0]
magn_ellipsoid_transform: [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 0.0
gyro_average_offset_y: 0.0
gyro_average_offset_z: 0.0
