## USB port
# port: /dev/ttyUSB1
port: /dev/rfcomm2
rawdata_filename: s03.csv
number_of_samples: 2000
# 1000 samples ~ 20 seconds; 2000 samples ~ 40 seconds; 3000 samples ~ 60 seconds



##default_data_stream_path: (dont use a relative path ~/catkin_ws/src/razor_imu_9dof)
main_data_stream_path: /home/map479/catkin_ws/src/razor_imu_9dof


# main_data_stream_path: /home/map479-admin/mxochicale/phd/ros/ros_razor/table_tennis/
# main_data_stream_path: /home/map479-admin/mxochicale/phd/ros/ros_razor/FourRazorsData


##### Calibration ####
### accelerometer
accel_x_min: -258.03
accel_x_max: 251.58
accel_y_min: -249.94
accel_y_max: 260.30
accel_z_min: -276.90
accel_z_max: 228.07



### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-5.50514, 97.0566, 50.5974]
magn_ellipsoid_transform: [[0.949220, -0.0141226, -0.0117998], [-0.0141226, 0.978607, 0.00336626], [-0.0117998, 0.00336626, 0.994728]]



# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -9.71
gyro_average_offset_y: 36.94
gyro_average_offset_z: 4.20
